### ISSUE TITLE
Error with 3' UTR Annotation

### ISSUE THREAD

**Issue by rsajulga-nmdp** [nmdp-bioinformatics/SeqAnn#150]
When the 3' UTR is missing, a line in the code does not account for this circumstance. The error is as follows:
```
Traceback (most recent call last):
  File "/gfe/seq2gfe", line 99, in <module>
    main()
  File "/gfe/seq2gfe", line 71, in main
    ann = seqann.annotate(seq, loc)
  File "/usr/local/lib/python3.7/site-packages/seqann/sequence_annotation.py", line 469, in annotate
    cutoff=align_cutoff)
  File "/usr/local/lib/python3.7/site-packages/seqann/sequence_annotation.py", line 775, in ref_align
    and 'three_prime_UTR' in annotation.annotation:
TypeError: argument of type 'NoneType' is not iterable
```

This is due to the following code chunk in `seqann/sequence_annotation.py` (starting at line 773):
```
if an.features[f].location.start == 0 \
        and f != "five_prime_UTR" \
        and 'three_prime_UTR' in annotation.annotation:
    del an.features[f]
    continue
```

**Comment by rsajulga-nmdp** [comment]
Solution suggested here: https://github.com/nmdp-bioinformatics/seq-ann/pull/151
